services:
  online-store:
    image: online-store:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-store
    ports:
      - "8000:8000"
    restart: always
    env_file:
        - .env
    volumes:
      - ./app:/app/
